### ISSUE TITLE
Selecting only partition column causes table scan in parquet-hive

### ISSUE THREAD

**Issue by billonahill** [prestodb/presto-admin#141]
```select min(datehour) from foo;``` will cause a full table scan on a table ```foo``` partitioned by ```datehour```. Instead the query should only scan the hive table metadata.

**Comment by cawallin** [comment]
@billonahill I think you meant to open this issue in facebook/presto rather than prestodb/presto-admin :)

**Comment by rschlussel** [comment]
You should this issue in facebook/presto

**Comment by billonahill** [comment]
Ugh. Thanks! :)
