### ISSUE TITLE
Add ability to specify a range or * for hosts in config.json

### ISSUE THREAD

**Issue by mattsfuller** [prestodb/presto-admin#247]
If you have a large cluster (say, 28 nodes), it's inconvenient to list out all of the nodes. We should provide a way to provide a range. (aka "hadoop-cluster-d[1-100]")

**Comment by yuokada** [comment]
Hi, @mattsfuller 
solved your problem?

**Comment by kokosing** [comment]
To me it is solved. @mattsfuller please reopen if you there is something missing.
