### ISSUE TITLE
setup.py has invalid url as "url" attribute

### ISSUE THREAD

**Issue by moshez** [prestodb/presto-admin#340]
In [setup.py](https://github.com/prestodb/presto-admin/blob/cf4dd6f15a16ca7edff01456c34575cd2fb78e04/setup.py#L101) the URL is     https://github.com/teradatalabs/presto-admin instead of https://github.com/prestodb/presto-admin

This link gets into [PyPI](https://pypi.python.org/pypi/prestoadmin/2.2) and makes it hard to find the source (luckily the README has the right URL).

**Comment by akshatnair** [comment]
We should replace it with https://github.com/Teradata/presto-admin
