### ISSUE TITLE
presto-admin server install ignores python

### ISSUE THREAD

**Issue by NickMcNutt** [prestodb/presto-admin#345]
I am trying to install Presto using presto-admin on Ubuntu 16.04.  I have installed packages rpm and python-dev; however, when I run `./presto-admin server install latest` I get the following error:

```
~/prestoadmin# ./presto-admin server install latest
Using rpm_specifier as "latest"
Fetching the latest presto rpm
Found existing rpm at: /tmp/presto-server-rpm-0.185.rpm
Found and using local presto rpm at path: /tmp/presto-server-rpm-0.185.rpm
Delete the existing rpm to force a new download
Deploying rpm on localhost...
Package deployed successfully on: localhost
[localhost] out: rpm: RPM should not be used directly install RPM packages, use Alien instead!
[localhost] out: rpm: However assuming you know what you are doing...
[localhost] out: error: Failed dependencies:
[localhost] out: 	python >= 2.4 is needed by presto-server-rpm-0:0.185-1.x86_64
[localhost] out: 	/usr/sbin/useradd is needed by presto-server-rpm-0:0.185-1.x86_64
[localhost] out: 	/usr/sbin/groupadd is needed by presto-server-rpm-0:0.185-1.x86_64
[localhost] out:

Fatal error: [localhost] sudo() received nonzero return code 1 while executing!

Requested: rpm -i /opt/prestoadmin/packages/presto-server-rpm-0.185.rpm
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "rpm -i /opt/prestoadmin/packages/presto-server-rpm-0.185.rpm"
```

But Python 2.7 is installed:

```
~/prestoadmin# python --version
Python 2.7.12
```

So when I try `./presto-admin server install latest --nodeps` I get another error:

```
./presto-admin server install latest --nodeps
Using rpm_specifier as "latest"
Fetching the latest presto rpm
Found existing rpm at: /tmp/presto-server-rpm-0.185.rpm
Found and using local presto rpm at path: /tmp/presto-server-rpm-0.185.rpm
Delete the existing rpm to force a new download
Deploying rpm on localhost...
Package deployed successfully on: localhost
[localhost] out: rpm: RPM should not be used directly install RPM packages, use Alien instead!
[localhost] out: rpm: However assuming you know what you are doing...
[localhost] out: /var/tmp/rpm-tmp.OddUis: 34: /var/tmp/rpm-tmp.OddUis: Syntax error: word unexpected (expecting ")")
[localhost] out: error: %prein(presto-server-rpm-0:0.185-1.x86_64) scriptlet failed, exit status 2
[localhost] out: error: presto-server-rpm-0:0.185-1.x86_64: install failed
[localhost] out:

Fatal error: [localhost] sudo() received nonzero return code 1 while executing!

Requested: rpm -i --nodeps /opt/prestoadmin/packages/presto-server-rpm-0.185.rpm
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "rpm -i --nodeps /opt/prestoadmin/packages/presto-server-rpm-0.185.rpm"
```

Any idea on what's going on?

**Comment by yuokada** [comment]
Hi, you can't install rpm package in Ubuntu.
presto-admin is designed for RPM-based Linux (RHEL, CentOS, Fedora).

**Comment by petroav** [comment]
@NickMcNutt thank you for using `presto-admin` :)

Unfortunately, since you're on Ubuntu you won't be able to use `presto-admin` since `presto-admin` can only install Presto using the RPM utility which is a package manager that only works on RHEL/Centos Linux flavors. See the operating systems requirement in the docs https://prestodb.io/presto-admin/docs/current/software-requirements.html.

We currently have no plans to add support in `presto-admin` for installing Presto using `tar.gz` but hopefully if the `presto-manager` project moves along then you'll be able to use it on Ubuntu.

**Comment by NickMcNutt** [comment]
Thanks for the help.  I was looking at a different prerequisites page then.  Does this page need updating to remove the Ubuntu reference?

https://prestodb.io/presto-admin/docs/current/installation/presto-admin-installation.html

**Comment by petroav** [comment]
That page is for installing `presto-admin` itself. The utility can run on Ubuntu, it is Presto that cannot be installed on Ubuntu. So for example, your client machine can run Ubuntu and you can have `presto-admin` installed on it but your cluster where you install Presto would have to be RHEL/Centos.

**Comment by NickMcNutt** [comment]
Ah, alright.  That clarifies things.  Thank you for the help.
