### ISSUE TITLE
Update docker-py to 2.6.0 from 1.5.0

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto-admin#348]
When using current docker version and old docker-py it is possible to get some weird errors. I am getting this one:

```
"Cannot link to a non running container
```

[Here](https://stackoverflow.com/a/46849399/217852) someone suggest that we sholuld use `docker network` instead of link. 

Update would be nice, but it is hard to tell how much changes are needed to update this lib.

**Comment by petroav** [comment]
Are you getting the error while running the product tests?

I feel like as long as the two versions are API compatible everything should work as expected. Did you try a Travis run with the new version?

**Comment by kokosing** [comment]
Yes, I got this error while running product tests. I haven't yet started to do anything with the new version.

**Comment by kokosing** [comment]
Fixed with #353
