### ISSUE TITLE
Online installer is not working when built from repo on Ubuntu 14.04

### ISSUE THREAD

**Issue by gazing-star** [prestodb/presto-admin#37]
amrutag@amrutag-devenv-precise64:~/bin/prestoadmin$ sudo ./presto-admin --help

Traceback (most recent call last):
  File "/home/amrutag/bin/prestoadmin/presto-admin-install/bin/presto-admin", line 7, in <module>
    from prestoadmin.main import main
ImportError: No module named prestoadmin.main

When built from the repo, no module named "prestoadmin" is created in the directory "INSTALL_DIR/prestoadmin/presto-admin-install/lib/python2.7/site-packages/"

**Comment by cawallin** [comment]
It worked for me when I tried the online installer locally.  It could be something you're missing with your setup, or a different library version. can you do pip freeze in your virtualenv?

**Comment by gazing-star** [comment]
Well, this was specific to my setup, since I had some half-built directory tree.
