### ISSUE TITLE
offline installation clarification

### ISSUE THREAD

**Issue by goodsoul1914** [prestodb/presto-admin#376]
hi there,
in readme for offline install stated that prestoadmin-<version>-offline.tar.gz file should be downloaded and `install-prestoadmin.sh` file should be executed. but I dont see any of these files in repo. what I am missing? thank you.

**Comment by RootG** [comment]
Hi, you are right, documents do not mention where to download offline files. You can find them in releases section of GitHub. I included the link below anyway.

https://github.com/prestodb/presto-admin/releases
