### ISSUE TITLE
presto-admin catalog command not found

### ISSUE THREAD

**Issue by niraj8241** [prestodb/presto-admin#377]
This is not an issue but I recently downloaded the online installer, I can't seem to find the catalog add command. Am I missing something?

[ec2-user@ip-172-31-1-29 bin]$ sudo ./presto-admin catalog add hive

Warning: Command not found:
    catalog add hive

[ec2-user@ip-172-31-1-29 bin]$ sudo ./presto-admin --version
presto-admin 1.4.2

OS: AWS EMR

**Comment by findepi** [comment]
> presto-admin 1.4.2

this is very old. The newest is 2.5.1. I am therefore closing the issue.

BTW I don't think Facebook Presto team maintains `presto-admin` project.
I would suggest that you consider migrating away from it.
For AWS, you can use Starburst Presto packaged for AWS (https://www.starburstdata.com/presto-aws-cloud/) which does not depend on presto-admin.
