### ISSUE TITLE
Install script tests importability of Paramiko incorrectly

### ISSUE THREAD

**Issue by grepwood** [prestodb/presto-admin#60]
```
root@presto-server:/opt/prestoadmin# python -c "import lol" 2>&1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lol
root@presto-server:/opt/prestoadmin# echo $?
1
root@presto-server:/opt/prestoadmin# python -c "import paramiko" 2>&1
root@presto-server:/opt/prestoadmin# echo $?
0
```
This is just so we know, that on success the command will return 0 rather than 1.
Take a look at https://github.com/prestodb/presto-admin/blob/master/packaging/install-prestoadmin.template#L40
```
if ! `python -c "import paramiko" > /dev/null 2>&1` ; then
```
The "!" needs not to be there. This test will pass when importing Paramiko succeeds, which is not correct because we get told the following:
```
printf "\nERROR\n"
echo "Paramiko could not be imported. This usually means that pycrypto (a dependency of paramiko)"
echo "has been compiled against a different libc version. Ensure the presto-admin installer is "
echo "built on the same OS as the target installation OS."
exit 1
```

**Comment by cawallin** [comment]
What OS are you using for presto-admin? For the offline installer (which is the default) we compile pycrypto with the library files for CentOS/RHEL, so if you want to run on a different OS, you need to use the online installer.

I think we have tests for the case you mentioned (e.g. https://github.com/prestodb/presto-admin/blob/master/tests/product/test_installation.py#L89 and others in that file), but I will also look into it.

**Comment by grepwood** [comment]
Ubuntu 14.04

**Comment by cawallin** [comment]
I will update the README to be clearer about the fact that by default it's compiled for CentOS, and file an issue about managing better what OS presto-admin is compiled against (it's complicated by the fact that we have an offline installer, since sometimes that's a requirement in customer sites, because pycrypto is a C library and thus needs the proper C header files for the given OS). Glad you're giving presto-admin a try!

**Comment by talisman027** [comment]
I get the above error while trying to install to CentOS 7. It looks like presto-admin is complied in a CentOS 6 box. How can I resolve the problem?

**Comment by mattsfuller** [comment]
Hi -- yes. The "offline installer" is built against CentOS 6. You'd have to build the the offline installer on a CentOS 7 box or docker image. Or you can use the "online installer" that will simply build the deps on the CentOS location you're installer.

What version of Presto Admin are you trying to use? If it's easy enough, I can see about uploading the CentOS 7 compatible artifact.

**Comment by talisman027** [comment]
@mattsfuller thanks for the quick reply. I'm using admin version 2.3. I just tried the online installer but it fails for another reason which I'm looking into now.

`Error: command 'gcc' failed`

**Comment by mattsfuller** [comment]
You'll have to install gcc on that machine. There's probably a number of other tools. If you do:
yum groupinstall "Development Tools" it should cover everything you need.

**Comment by sushilrbs** [comment]
Do we have prestoadmin offline installer for redhat 7.*?

**Comment by mattsfuller** [comment]
There is one prebuilt on Starburst's download page. www.starburstdata.com. Then click on "Try Presto" it will bring you to the page with that download.
