### ISSUE TITLE
Support for 'package uninstall'

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto-admin#68]
As there is 'package install', but no support 'package uninstall' or 'update', So there is no way to update a package.

**Comment by cawallin** [comment]
@kokosing that should be a small change, would you be interested/willing to add it yourself?

**Comment by cawallin** [comment]
'package uninstall' should be quite similar to 'package install'.  It needs to uninstall a given RPM package on all of the nodes of the cluster.

A few notes:
* presto-admin is based on Fabric (http://docs.fabfile.org/en/1.10/), and most of the annotations are from Fabric.
* The @runs_once annotation requires some trickery to make the unit tests work correctly; check out other unit tests that use that annotation to see the way to get around it
* In addition to unit tests, we write product tests for presto-admin. These run on a docker cluster that the tests create locally, and can be run via `make test-all` (optionally, you can specify the suite -- aka tests.product.test_package_install -- to run only the relevant tests). They are located in tests/product.

**Comment by kokosing** [comment]
Fixed by https://github.com/prestodb/presto-admin/commit/502de6532f135111c250a880e46d5cf68c7f3ab2
