### ISSUE TITLE
Possible error in automatically filling out config.json

### ISSUE THREAD

**Issue by petroav** [prestodb/presto-admin#87]
During server start presto-admin gives the following error message:

```
Fatal error: coercing to Unicode: need string or buffer, int found

Underlying exception:
    coercing to Unicode: need string or buffer, int found

Aborting.
```

Putting double quotes around the port number in `/etc/opt/prestoadmin/config.json` fixed the issue.

**Comment by rschlussel** [comment]
Is this when the config was set interactively?

**Comment by petroav** [comment]
Yes.

**Comment by rschlussel** [comment]
Fixed by https://github.com/prestodb/presto-admin/issues/88
