### ISSUE TITLE
error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by kyleburke** [prestodb/presto-admin#91]
When I try to perform a "make dist-online" or "make dist" I get an "invalid command bdist_wheel" error. Below is my environment information. Any ideas how to get around the issue? 

LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
NAME="Amazon Linux AMI"
VERSION="2015.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2015.03"
PRETTY_NAME="Amazon Linux AMI 2015.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2015.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2015.03

**Comment by petroav** [comment]
You probably don't have `wheel` installed. To install it you can run `pip install wheel`. In the `presto-admin` repo there's a `requirements.txt` file that has all the various requirements needed to build/develop `presto-admin`. To install all the requirements you can run `pip install -r requirements.txt`. I recommend you do that in a virtualenv so as not to pollute your global python packages. Let us know if you're still having trouble.

**Comment by mattsfuller** [comment]
@kyleburke did you get this working?

**Comment by kyleburke** [comment]
Yes, the install wheel fixed my issue.

**Comment by mattsfuller** [comment]
Great!
